name: build & upload

on: 
   workflow_dispatch:

jobs:
   build:
      name: Build
      runs-on: macOS-latest
      steps:
         - name: Checkout the Repo
           uses: actions/checkout@main
         - name: Install ldid
           uses: MOZGIII/install-ldid-action@v1
           with:
              tag: v2.1.5-procursus7
         - name: Run script
           run: |
             cd ${{ GITHUB.WORKSPACE }} & sh ./build.sh